clone:
  git:
    image: plugins/git:next
    pull: true

pipeline:
  publish_wheel:
    image: spscommerce/drone-plugin-python-artifactory
    action: publish
    build_package: true
    when:
      event: [tag]
      branch: develop
