clone:
  git:
    image: plugins/git:next
    pull: true

pipeline:
  tests:
    image: python:3.7-alpine3.8
    commands:
      - apk --update add python3-dev linux-headers build-base
      - pip install -r requirements/requirements-test.txt
      - pytest
    when:
      event: [push, pull_request]
      branch: master

  tag:
    image: spscommerce/plugin-semantic-release
    when:
      event: push
      branch:
        - master

  publish_wheel:
    image: spscommerce/drone-plugin-python-artifactory
    action: publish
    build_package: true
    when:
      event: [tag]
      branch: master
